version: "3.7"
services:
  node-express:
    build: 
      context: ./node-express
      args:
        - PORT=3000
    environment:
      - NODE_ENV=test
    ports:
      - "3000:3000"
  next-app:
    build: ./next-app
    ports:
      - "80:3000"
    depends_on:
      - node-express
